CREATE TABLE IF NOT EXISTS BankHesaplar (
    Nickname VARCHAR(30) PRIMARY KEY,
    Balance DECIMAL(14,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BankIslemleri (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nickname VARCHAR(30) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    asset_name VARCHAR(64) DEFAULT NULL,
    note VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Krediler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nickname VARCHAR(30) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    term_months INT NOT NULL,
    monthly_payment DECIMAL(14,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    remaining_principal DECIMAL(14,2) NOT NULL DEFAULT 0,
    interest_rate DECIMAL(6,2) NOT NULL DEFAULT 5.00,
    months_paid INT NOT NULL DEFAULT 0,
    months_remaining INT NOT NULL DEFAULT 0,
    last_payment_at TIMESTAMP NULL DEFAULT NULL,
    next_due_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DestekTalepleri (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nickname VARCHAR(30) NOT NULL,
    subject VARCHAR(120) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    admin_reply TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BankTransfers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_nickname VARCHAR(30) NOT NULL,
    sender_number CHAR(8) NOT NULL,
    receiver_nickname VARCHAR(30) NOT NULL,
    receiver_number CHAR(8) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    note VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MarketVarliklari (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_class VARCHAR(20) NOT NULL,
    name VARCHAR(80) NOT NULL,
    symbol VARCHAR(40) DEFAULT NULL,
    current_price DECIMAL(14,2) NOT NULL,
    base_price DECIMAL(14,2) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MarketFiyatDegisimleri (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_id INT NOT NULL,
    old_price DECIMAL(14,2) NOT NULL,
    new_price DECIMAL(14,2) NOT NULL,
    change_amount DECIMAL(14,2) NOT NULL,
    change_percent DECIMAL(8,2) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BankBildirimleri (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nickname VARCHAR(30) NOT NULL,
    notice_type VARCHAR(20) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    description TEXT DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
    due_at TIMESTAMP NULL DEFAULT NULL,
    paid_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KullaniciVarliklari (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nickname VARCHAR(30) NOT NULL,
    asset_class VARCHAR(20) NOT NULL,
    asset_name VARCHAR(80) NOT NULL,
    symbol VARCHAR(40) DEFAULT NULL,
    quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    average_price DECIMAL(14,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UygulamaLoglari (
    id INT AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(20) NOT NULL,
    level_name VARCHAR(20) NOT NULL,
    event_name VARCHAR(80) NOT NULL,
    detail TEXT DEFAULT NULL,
    nickname VARCHAR(30) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
